# Generated by Django 4.0.7 on 2022-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
