# Generated by Django 4.0.7 on 2022-12-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_leasing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdetails',
            old_name='First_Name',
            new_name='First_N',
        ),
        migrations.RenameField(
            model_name='registerdetails',
            old_name='Phone_Number',
            new_name='Last_N',
        ),
        migrations.RenameField(
            model_name='registerdetails',
            old_name='Last_Name',
            new_name='Phone_Num',
        ),
    ]
