# Generated by Django 4.0.7 on 2022-12-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_leasing_app', '0003_rename_first_n_registerdetails_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdetails',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='registerdetails',
            old_name='Last_Name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='registerdetails',
            old_name='Phone_Number',
            new_name='PhoneNumber',
        ),
    ]
