# Generated by Django 4.0.7 on 2022-12-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_leasing_app', '0005_lesseedetails_lessordetails_delete_registerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesseedetails',
            old_name='Phone_No',
            new_name='Phone_Number',
        ),
    ]
