# Generated by Django 4.0.7 on 2023-01-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_leasing_app', '0006_rename_phone_no_lesseedetails_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessordetails',
            old_name='Phone_No',
            new_name='Phone_Number',
        ),
    ]
