# Generated by Django 4.0.7 on 2023-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_leasing_app', '0007_rename_phone_no_lessordetails_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Container_Type', models.CharField(max_length=50)),
                ('Container_Size', models.CharField(max_length=10)),
                ('Container_Picture', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Container_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessee_id', models.IntegerField()),
                ('Lessee_Name', models.CharField(max_length=20)),
                ('Owner_id', models.IntegerField()),
                ('Owner_Name', models.CharField(max_length=20)),
                ('Lease_Container_Type', models.CharField(max_length=50)),
                ('Lease_Container_Size', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Lease_Date', models.DateTimeField()),
                ('Leasing_Months', models.IntegerField()),
                ('Lease_Amount', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
